[package]
name = "goval_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
# async-log = "2.0.0"
async-trait = "0.1.66"
# base64 = "0.21.0"
c-map = "0.2.1"
console-subscriber = "0.1.8"
deadqueue = "0.2.4"
deno_core = "0.157.0"
env_logger = "0.10.0"
futures-channel = "0.3.26"
futures-util = "0.3.26"
lazy_static = "1.4.0"
log = "0.4.17"
prost = "0.11.8"
prost-types = "0.11.8"
# serde_v8 = "0.67.0"
serde_json = "1.0.96"
serde = "1.0.162"
tokio = {version="1.26.0", features = ["full"]}
tokio-tungstenite = "0.18.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
# deno_runtime = "0.69.0"

[build-dependencies]
prost-build = "0.11.8"
# deno_core = "0.174.0"
