[package]
name = "homeval"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"] # "entity", 

[dependencies]
async-trait = "0.1.66"
c-map = { version = "0.2.1", features=["parking-lot"]}
console-subscriber = "0.1.8"
deadqueue = "0.2.4"
deno_core = "0.157.0"
env_logger = "0.10.0"
futures-channel = "0.3.26"
futures-util = "0.3.26"
lazy_static = "1.4.0"
log = "0.4.17"
prost = "0.11.8"
prost-types = "0.11.8"
serde_json = "1.0.96"
serde = "1.0.162"
tokio = {version="1.26.0", features = ["full"]}
tokio-tungstenite = "0.18.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
base64 = "0.21.0"
portable-pty = "0.8.1"
sea-orm = { version = "0.11.3", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
async_once = "0.2.6"

migration = { path = "migration" }

include_directory = { git = "https://github.com/goval-community/include_directory.git" }

[build-dependencies]
prost-build = "0.11.8"

