[package]
name = "homeval"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["PotentialStyx <62217716+PotentialStyx@users.noreply.github.com>"]
repository = "https://github.com/goval-community/homeval/"
description = """A custom implementation of replits evaluation protocol.
See https://govaldocs.pages.dev"""

[features]
default = ["replspace"]
replspace = ["axum"]
fun-stuff = ["chrono", "chrono-tz"]

[dependencies]
deno_core = "0.189.0"
env_logger = "0.10.0"
futures-channel = "0.3.26"
futures-util = "0.3.26"
lazy_static = "1.4.0"
log = "0.4.17"
prost = "0.11.8"
prost-types = "0.11.8"
serde_json = "1.0.96"
serde = "1.0.162"
tokio = {version="1.26.0", features = ["full"]}
tokio-tungstenite = "0.18.0"
tokio-stream = { version = "0.1.14", features = ["fs"] }
base64 = "0.21.0"
portable-pty = "0.8.1"

include_directory = { git = "https://github.com/goval-community/include_directory.git", rev = "bea5083a" }
futures = "0.3.28"
os_pipe = "1.1.4"
axum = { version = "0.6.18", optional = true }
systemstat = "0.2.3"
cpu-time = "1.0.0"
notify-debouncer-full = { version = "0.1.0", default-features = false, features = ["serde"] }
deadqueue = { version = "0.2.4", default-features = false, features = ["unlimited"] }
similar = "2.2.1"
prost-wkt-types = { git = "https://github.com/fdeantoni/prost-wkt/", rev="15bc0a06"}
toml = "0.7.4"
chrono = { version = "0.4.26", default-features = false, features = ["time", "std", "libc", "clock"], optional = true }
chrono-tz =  { version = "0.8.2", optional = true }
textnonce = "1.0.0"

[build-dependencies]
prost-build = "0.11.8"
