#!/usr/bin/env bash
set -eou pipefail

[[ "$1" == "Username for 'https://github.com': " ]] && echo "token" && exit 0
[[ "$1" != "Password for 'https://token@github.com': " ]] && exit 1

TOKEN=$(curl -s "localhost:8283/github/token?channel=$REPLIT_GIT_ASKPASS_GODS_PLS_SEND_TO_RIGHT_SESSION_SHELL_TOKEN" | tr \{ '\n' | tr , '\n' | tr \} '\n' | grep "token" | awk -F'"' '{print $4}') || echo ""

[[ -z "$TOKEN" ]] && >&2 echo "Unable to get your GitHub token from Replit, please connect your GitHub account at https://replit.com/account" && exit 1

echo "$TOKEN"